import { useCallback, useEffect, useMemo, useState } from "react";
import { Avatar, Button, Input, Modal, Popconfirm, Select, Switch, message } from "antd";
import { CloseOutlined, DeleteOutlined, HeartFilled, HeartOutlined, MessageOutlined, MoreOutlined, PictureOutlined, ReloadOutlined, SendOutlined, UserOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import { useAuth } from "../../store/AuthContext";
import { useNavigate, useParams } from "react-router-dom";
import { createCfsPost, createCfsReply, deleteCfsPost, deleteCfsReply, getCfsIdentity, getCfsPost, getCfsPosts, setCfsIdentity, toggleCfsLike, toggleCfsReplyLike, uploadCfsImage } from "../../services/cfs.service";
import { onCfsChanged, onOnlineUsers } from "../../services/socket";
import "./Cfs.css";

const timeAgo = (value) => { const minutes = Math.floor(Math.max(0, Date.now() - new Date(value).getTime()) / 60000); if (minutes < 1) return "vừa xong"; if (minutes < 60) return `${minutes}p`; if (minutes < 1440) return `${Math.floor(minutes / 60)}h`; return dayjs(value).format("DD/MM/YYYY"); };
const CfsAvatar = ({ author, size = 40, online = false }) => <span className="cfs-avatar-wrap"><Avatar size={size} src={author?.avatar || undefined} className={author?.anonymous ? "cfs-avatar cfs-avatar-anonymous" : "cfs-avatar"}>{author?.anonymous ? "?" : <UserOutlined />}</Avatar>{online && <i className="cfs-online-dot" />}</span>;
const Author = ({ author, createdAt, admin, isPostAuthor = false }) => <div className="cfs-author"><span>{author?.name}</span>{author?.anonymous && <em>ẩn danh</em>}<time>· {timeAgo(createdAt)}</time>{isPostAuthor && <b>Tác giả</b>}{admin && author?.identity && <small>Admin: {author.identity.fullName} · @{author.identity.username}</small>}</div>;
const PostHeader = ({ author, createdAt, admin }) => <div className="cfs-post-header"><Author author={author} createdAt={createdAt} admin={admin} /><button type="button" className="cfs-more-action" aria-label="Tùy chọn bài viết"><MoreOutlined /></button></div>;
const groupReplies = (replies) => replies.reduce((groups, reply) => { const key = String(reply.parentReplyId || "root"); (groups[key] ||= []).push(reply); return groups; }, {});
const AnonymousToggle = ({ enabled, alias, onChange }) => { const [uploading, setUploading] = useState(false); const uploadImage = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setUploading(true); const response = await uploadCfsImage(file); const url = response.data?.data?.url || ""; if (!url) throw new Error("Không nhận được URL ảnh"); window.dispatchEvent(new CustomEvent("cfs:image-selected", { detail: url })); message.success("Đã thêm ảnh vào bài viết"); } catch { message.error("Không thể tải ảnh lên"); } finally { setUploading(false); event.target.value = ""; } }; return <div className="cfs-anon-control"><span>Đăng ẩn danh</span><Switch size="small" checked={enabled} onChange={onChange} /><label className="cfs-image-picker" title="Thêm ảnh"><PictureOutlined /><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={uploadImage} disabled={uploading} /></label>{enabled && alias && <small>Biệt danh: {alias}</small>}</div>; };

const Replies = ({ replies, admin, onlineUsers, onReply, onLike, onDelete, sortMode }) => {
  const groups = useMemo(() => groupReplies(replies), [replies]);
  const childrenOf = (id) => (groups[String(id)] || []).slice().sort((a, b) => sortMode === "top" ? (b.likes - a.likes) || (new Date(b.createdAt) - new Date(a.createdAt)) : new Date(b.createdAt) - new Date(a.createdAt));
  const renderReply = (reply, depth = 0, replyingTo) => <div className={`cfs-reply-branch ${depth ? "is-nested" : ""}`} key={reply._id} style={{ "--reply-depth": depth }}><div className="cfs-reply"><CfsAvatar author={reply.author} size={30} online={onlineUsers.has(String(reply.author?.userId))} /><div className="cfs-reply-content">{replyingTo && <div className="cfs-reply-context"><CfsAvatar author={replyingTo} size={18} /><span>Trả lời <strong>{replyingTo.name}</strong></span></div>}<Author author={reply.author} createdAt={reply.createdAt} admin={admin} isPostAuthor={reply.isPostAuthor} /><p>{reply.content}</p><div className="cfs-reply-actions"><button type="button" className={reply.liked ? "is-liked" : ""} onClick={() => onLike(reply)}>{reply.liked ? <HeartFilled /> : <HeartOutlined />}{reply.likes > 0 && <span>{reply.likes}</span>}</button><button type="button" onClick={() => onReply(reply)}>Trả lời</button>{reply.canManage && <Popconfirm title="Xóa phản hồi này?" description="Các phản hồi bên dưới cũng sẽ bị xóa." okText="Xóa" cancelText="Hủy" onConfirm={() => onDelete(reply._id)}><button type="button" className="cfs-delete-action" aria-label="Xóa phản hồi"><DeleteOutlined /></button></Popconfirm>}</div></div></div></div>;
  const flattenChildren = (parent) => childrenOf(parent._id).flatMap((child) => [renderReply(child, 1, parent.author), ...flattenChildren(child)]);
  return childrenOf("root").flatMap((reply) => [renderReply(reply), ...flattenChildren(reply)]);
};

const PostActions = ({ post, onLike, onOpenReplies, showDelete, onDelete }) => <>{post.imageUrl && <img className="cfs-post-image" src={post.imageUrl} alt="Ảnh bài viết" />}<div className="cfs-actions"><button type="button" aria-label="Thích bài viết" className={post.liked ? "is-liked" : ""} onClick={() => onLike(post._id)}>{post.liked ? <HeartFilled /> : <HeartOutlined />}{post.likes > 0 && <span>{post.likes}</span>}</button>{post.likeUsers?.length > 0 && <span className="cfs-like-avatars" title={post.likeUsers.map((user) => user.name).join(", ")}>{post.likeUsers.slice(0, 2).map((user) => <Avatar key={String(user._id)} size={18} src={user.avatar || undefined}>{user.name.slice(0, 1)}</Avatar>)}{post.likeUsers.length > 2 && <b>+{post.likeUsers.length - 2}</b>}</span>}<button type="button" aria-label="Xem bình luận" onClick={onOpenReplies}><MessageOutlined />{post.replies?.length > 0 && <span>{post.replies.length}</span>}</button>{showDelete && <Popconfirm title="Xóa bài viết này?" description="Toàn bộ phản hồi cũng sẽ bị xóa." okText="Xóa" cancelText="Hủy" onConfirm={() => onDelete(post._id)}><button type="button" className="cfs-delete-action" aria-label="Xóa bài viết"><DeleteOutlined /></button></Popconfirm>}</div></>;

const DetailPage = ({ post, onClose, admin, onlineUsers, viewer, onLike, onDeletePost, onDeleteReply, onLikeReply, replyingTo, setReplyingTo, replyContent, setReplyContent, replyAnonymous, setReplyAnonymous, alias, requestAnonymous, onSendReply, replySort, setReplySort }) => post && <div className="cfs-page cfs-detail-page">
  {post && <div className={`cfs-detail ${post.replies?.length ? "" : "is-empty"}`}><header className="cfs-detail-header"><Button type="text" icon={<CloseOutlined />} onClick={onClose}>Đóng</Button><strong>Bài viết</strong><span /></header><div className="cfs-detail-scroll"><article className="cfs-post cfs-detail-post"><div className="cfs-post-grid"><CfsAvatar author={post.author} online={onlineUsers.has(String(post.author?.userId))} /><div className="cfs-post-body"><PostHeader author={post.author} createdAt={post.createdAt} admin={admin} /><p>{post.content}</p><PostActions post={post} onLike={onLike} onOpenReplies={() => {}} showDelete={post.canManage} onDelete={onDeletePost} /></div></div></article><div className="cfs-detail-sort"><Select size="small" variant="borderless" value={replySort} onChange={setReplySort} options={[{ value: "top", label: "↕ Hàng đầu" }, { value: "newest", label: "Mới nhất" }]} /><span>{post.replies?.length || 0} phản hồi</span></div><section className="cfs-replies cfs-detail-replies"><Replies replies={post.replies || []} sortMode={replySort} admin={admin} onlineUsers={onlineUsers} onReply={(reply) => setReplyingTo({ postId: post._id, parentReplyId: reply._id, name: reply.author.name })} onDelete={(replyId) => onDeleteReply(post._id, replyId)} onLike={(reply) => onLikeReply(post._id, reply)} /></section></div><footer className="cfs-detail-composer"><CfsAvatar author={{ avatar: viewer?.avatar }} size={32} /><div><Input.TextArea value={replyContent} onChange={(event) => setReplyContent(event.target.value)} placeholder={replyingTo ? `Trả lời ${replyingTo.name}...` : `Trả lời ${post.author.name}...`} autoSize={{ minRows: 1, maxRows: 3 }} maxLength={1000} /><div className="cfs-reply-footer"><AnonymousToggle enabled={replyAnonymous} alias={alias} onChange={(value) => requestAnonymous(value, "reply")} /><Button type="primary" size="small" disabled={!replyContent.trim()} onClick={onSendReply}>Gửi</Button></div></div></footer></div>}
</div>;
const DetailModal = DetailPage;

const Cfs = () => {
  const { user } = useAuth();
  const { postId } = useParams();
  const navigate = useNavigate();
  const [posts, setPosts] = useState([]); const [loading, setLoading] = useState(true); const [content, setContent] = useState(""); const [imageUrl, setImageUrl] = useState(""); const [anonymous, setAnonymous] = useState(false); const [alias, setAlias] = useState(""); const [aliasDraft, setAliasDraft] = useState(""); const [aliasModalOpen, setAliasModalOpen] = useState(false); const [aliasTarget, setAliasTarget] = useState(null); const [savingAlias, setSavingAlias] = useState(false); const [submitting, setSubmitting] = useState(false); const [detailPost, setDetailPost] = useState(null); const [replyingTo, setReplyingTo] = useState(null); const [replyContent, setReplyContent] = useState(""); const [replyAnonymous, setReplyAnonymous] = useState(false); const [replySort, setReplySort] = useState("top"); const [onlineUsers, setOnlineUsers] = useState(() => new Set()); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ totalPages: 1 }); const [, setClock] = useState(Date.now());
  const displayName = useMemo(() => user?.fullName || user?.username || "Bạn", [user]);
  const loadPosts = useCallback(async (requestedPage = page, showLoading = true) => { try { if (showLoading) setLoading(true); const response = await getCfsPosts({ page: requestedPage, limit: 100 }); setPosts(response.data?.data?.posts || []); setPagination(response.data?.data?.pagination || { totalPages: 1 }); } catch { message.error("Không thể tải bảng tin CFS"); } finally { if (showLoading) setLoading(false); } }, [page]);
  useEffect(() => { loadPosts(page); }, [page, loadPosts]); useEffect(() => onOnlineUsers(({ userIds }) => setOnlineUsers(new Set(userIds))), []); useEffect(() => onCfsChanged(() => { loadPosts(page, false); if (postId) getCfsPost(postId).then((response) => setDetailPost(response.data?.data?.post || null)).catch(() => {}); }), [loadPosts, page, postId]); useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 60000); return () => window.clearInterval(timer); }, []); useEffect(() => { getCfsIdentity().then((response) => setAlias(response.data?.data?.alias || "")).catch(() => message.error("Không thể kiểm tra biệt danh CFS")); }, []);
  useEffect(() => { const receiveImage = (event) => { if (event.detail) setImageUrl(event.detail); }; window.addEventListener("cfs:image-selected", receiveImage); return () => window.removeEventListener("cfs:image-selected", receiveImage); }, []);
  useEffect(() => { if (!postId) return setDetailPost(null); getCfsPost(postId).then((response) => setDetailPost(response.data?.data?.post || null)).catch(() => { message.error("Không thể tải bài viết"); navigate("/cfs", { replace: true }); }); }, [postId, navigate]);
  const requestAnonymous = (value, target) => { if (!value) return target === "post" ? setAnonymous(false) : setReplyAnonymous(false); if (alias) return target === "post" ? setAnonymous(true) : setReplyAnonymous(true); setAliasTarget(target); setAliasModalOpen(true); };
  const saveAlias = async () => { if (!aliasDraft.trim()) return message.warning("Hãy chọn một biệt danh"); try { setSavingAlias(true); const response = await setCfsIdentity(aliasDraft); setAlias(response.data?.data?.alias || aliasDraft.trim()); if (aliasTarget === "post") setAnonymous(true); else setReplyAnonymous(true); setAliasModalOpen(false); setAliasDraft(""); } catch (error) { message.error(error.response?.data?.message || "Không thể tạo biệt danh"); } finally { setSavingAlias(false); } };
  const confirmPublish = async () => { try { setSubmitting(true); const response = await createCfsPost({ content, imageUrl, isAnonymous: anonymous }); const post = response.data?.data?.post; setContent(""); setImageUrl(""); setAnonymous(false); if (post) setPosts((current) => [post, ...current.filter((item) => item._id !== post._id)]); message.success("Đã đăng bài"); } catch (error) { message.error(error.response?.data?.message || "Không thể đăng bài"); } finally { setSubmitting(false); } };
  const publish = () => { if (!content.trim() && !imageUrl) return message.warning("Viết điều bạn muốn chia sẻ hoặc chọn ảnh"); Modal.confirm({ title: "Xem trước bài viết", content: <div className="cfs-publish-preview">{imageUrl && <img src={imageUrl} alt="Ảnh xem trước" />}<p>{content || "Bài viết chỉ có ảnh"}</p>{anonymous && <small>Đăng bằng biệt danh: {alias}</small>}</div>, okText: "Đăng bài", cancelText: "Chỉnh sửa", onOk: confirmPublish }); };
  const like = async (id) => { const previous = posts; const previousDetail = detailPost; const toggle = (post) => post._id === id ? { ...post, liked: !post.liked, likes: post.likes + (post.liked ? -1 : 1) } : post; setPosts((current) => current.map(toggle)); setDetailPost((current) => current ? toggle(current) : current); try { await toggleCfsLike(id); } catch { setPosts(previous); setDetailPost(previousDetail); message.error("Không thể cập nhật lượt thích"); } };
  const removePost = async (targetPostId) => { try { await deleteCfsPost(targetPostId); if (postId === targetPostId) navigate("/cfs"); await loadPosts(page); message.success("Đã xóa bài viết"); } catch (error) { message.error(error.response?.data?.message || "Không thể xóa bài viết"); } };
  const removeReply = async (targetPostId, replyId) => { try { await deleteCfsReply(targetPostId, replyId); if (postId === targetPostId) { const response = await getCfsPost(targetPostId); setDetailPost(response.data?.data?.post || null); } await loadPosts(page); } catch (error) { message.error(error.response?.data?.message || "Không thể xóa phản hồi"); } };
  const likeReply = async (postId, reply) => { const previous = posts; setPosts((current) => current.map((post) => post._id === postId ? { ...post, replies: post.replies.map((item) => item._id === reply._id ? { ...item, liked: !item.liked, likes: item.likes + (item.liked ? -1 : 1) } : item) } : post)); try { await toggleCfsReplyLike(postId, reply._id); } catch { setPosts(previous); message.error("Không thể cập nhật lượt thích"); } };
  const sendReply = async () => { if (!replyContent.trim() || !postId) return; try { await createCfsReply(postId, { content: replyContent, isAnonymous: replyAnonymous, parentReplyId: replyingTo?.parentReplyId || null }); setReplyingTo(null); setReplyContent(""); setReplyAnonymous(false); const response = await getCfsPost(postId); setDetailPost(response.data?.data?.post || null); await loadPosts(page); } catch (error) { message.error(error.response?.data?.message || "Không thể gửi phản hồi"); } };
  const setDetailPostId = (id) => navigate(`/cfs/${id}`);
  if (postId) return <DetailPage post={detailPost} onClose={() => navigate("/cfs")} admin={user?.role === "admin"} onlineUsers={onlineUsers} viewer={user} onLike={like} onDeletePost={removePost} onDeleteReply={removeReply} onLikeReply={likeReply} replyingTo={replyingTo} setReplyingTo={setReplyingTo} replyContent={replyContent} setReplyContent={setReplyContent} replyAnonymous={replyAnonymous} setReplyAnonymous={setReplyAnonymous} alias={alias} requestAnonymous={requestAnonymous} onSendReply={sendReply} replySort={replySort} setReplySort={setReplySort} />;
  return <div className="cfs-page pb-24 lg:pb-0"><header className="cfs-hero"><div><span>Cộng đồng nội bộ</span><h1>Yakiuo CFS</h1></div><Button type="text" icon={<ReloadOutlined />} onClick={() => loadPosts(page)} loading={loading}>Làm mới</Button></header><div className="cfs-layout"><main className="cfs-feed"><section className="cfs-composer"><Avatar size={40} src={user?.avatar || undefined}>{displayName.slice(0, 1)}</Avatar><div className="cfs-composer-main"><Input.TextArea value={content} onChange={(event) => setContent(event.target.value)} placeholder={`${displayName} đang nghĩ gì?`} autoSize={{ minRows: 1, maxRows: 5 }} maxLength={2000} /><div className="cfs-composer-footer"><AnonymousToggle enabled={anonymous} alias={alias} onChange={(value) => requestAnonymous(value, "post")} /><Button type="primary" icon={<SendOutlined />} onClick={publish} loading={submitting} disabled={!content.trim()}>Đăng</Button></div></div></section>{loading ? <div className="cfs-loading">Đang tải bài viết...</div> : posts.length === 0 ? <div className="cfs-empty">Chưa có bài viết nào. Hãy mở đầu cuộc trò chuyện nhé.</div> : posts.map((post) => <article className="cfs-post" key={post._id}><div className="cfs-post-grid"><CfsAvatar author={post.author} online={onlineUsers.has(String(post.author?.userId))} /><div className="cfs-post-body"><PostHeader author={post.author} createdAt={post.createdAt} admin={user?.role === "admin"} /><p>{post.content}</p><PostActions post={post} onLike={like} onOpenReplies={() => { setDetailPostId(post._id); setReplyingTo(null); setReplyContent(""); }} showDelete={post.canManage} onDelete={removePost} /></div></div></article>)}{pagination.totalPages > 1 && <nav className="cfs-pagination"><Button disabled={page === 1} onClick={() => setPage(page - 1)}>Trang trước</Button><span>Trang {page} / {pagination.totalPages}</span><Button disabled={page === pagination.totalPages} onClick={() => setPage(page + 1)}>Trang sau</Button></nav>}</main></div><DetailModal post={detailPost} open={Boolean(detailPost)} onClose={() => { setDetailPostId(null); setReplyingTo(null); }} admin={user?.role === "admin"} onlineUsers={onlineUsers} viewer={user} onLike={like} onDeletePost={removePost} onDeleteReply={removeReply} onLikeReply={likeReply} replyingTo={replyingTo} setReplyingTo={setReplyingTo} replyContent={replyContent} setReplyContent={setReplyContent} replyAnonymous={replyAnonymous} setReplyAnonymous={setReplyAnonymous} alias={alias} requestAnonymous={requestAnonymous} onSendReply={sendReply} /><Modal open={aliasModalOpen} title="Tạo biệt danh ẩn danh" onCancel={() => setAliasModalOpen(false)} footer={<Button type="primary" loading={savingAlias} onClick={saveAlias}>Xác nhận</Button>}><p className="cfs-alias-note">Biệt danh chỉ dùng khi bạn chọn đăng ẩn danh.</p><Input value={aliasDraft} onChange={(event) => setAliasDraft(event.target.value)} placeholder="Ví dụ: Mèo hay ngủ" maxLength={40} autoFocus onPressEnter={saveAlias} /></Modal></div>;
};
export default Cfs;
